name: kiko_getx_xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.5.4 #适配
  flutter_swiper_view: ^1.1.8 #轮播图
  dio: ^4.0.6 #网络请求
  flutter_staggered_grid_view: ^0.6.2 #瀑布流
  shared_preferences: ^2.0.15 #本地储存历史记录
  flutter_html: ^3.0.0-alpha.6 #html
  pin_code_fields: ^7.4.0 #验证码
  city_pickers: ^1.1.3 # 城市
  crypto: ^3.0.2
  tobias: ^2.4.1 #支付宝支付插件
  intl: ^0.17.0 # 年月日
  flutter_svg: ^1.0.0
  signature: ^5.3.0 #签名
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: MyIcon   #指定一个字体名 根据自己的需求定义
      fonts:
        - asset: assets/fonts/iconfont.ttf 
    - family: userIcon   #指定一个字体名 根据自己的需求定义
      fonts:
        - asset: assets/fonts/userIconfont.ttf   
  assets:
    - assets/images/xiaomiBanner.png
    - assets/images/2.0x/xiaomiBanner.png
    - assets/images/3.0x/xiaomiBanner.png
    - assets/images/xiaomiBanner2.png
    - assets/images/2.0x/xiaomiBanner2.png
    - assets/images/3.0x/xiaomiBanner2.png
    - assets/images/hot_search.png
    - assets/images/2.0x/hot_search.png
    - assets/images/3.0x/hot_search.png 
    - assets/images/service.png
    - assets/images/2.0x/service.png
    - assets/images/3.0x/service.png
    - assets/images/user.png
    - assets/images/2.0x/user.png
    - assets/images/3.0x/user.png
    - assets/images/user_ad1.png
    - assets/images/2.0x/user_ad1.png
    - assets/images/3.0x/user_ad1.png    
    - assets/images/user_ad2.png
    - assets/images/2.0x/user_ad2.png
    - assets/images/3.0x/user_ad2.png 
    - assets/images/logo.png
    - assets/images/2.0x/logo.png
    - assets/images/3.0x/logo.png   
    - assets/images/default_avatar.png
    - assets/images/background_cat.png
    - assets/images/bottom_navigation_home.png
    - assets/images/shopping_bag.png
    - assets/images/2.0x/shopping_bag.png
    - assets/images/3.0x/shopping_bag.png
    - assets/images/planet_streamline.png
    - assets/images/2.0x/planet_streamline.png
    - assets/images/3.0x/planet_streamline.png
    - assets/images/chat_round.png
    - assets/images/2.0x/chat_round.png
    - assets/images/3.0x/chat_round.png
    - assets/images/me_pet_paw.png
    - assets/images/2.0x/me_pet_paw.png
    - assets/images/3.0x/me_pet_paw.png
    - assets/images/home_page_avatar.png
    - assets/svg/modify_info.svg
    - assets/svg/modify_add.svg
    - assets/svg/modify_tag_group.svg
    - assets/images/home_calendar.png
    - assets/images/2.0x/home_calendar.png
    - assets/images/3.0x/home_calendar.png
    - assets/svg/modify_bell_1.svg
    - assets/svg/modify_bell_2.svg
    - assets/images/home_advertising_picture.png
    - assets/images/2.0x/home_advertising_picture.png
    - assets/images/3.0x/home_advertising_picture.png
    - assets/images/consultation_icon_1.png
    - assets/images/2.0x/consultation_icon_1.png
    - assets/images/3.0x/consultation_icon_1.png
    - assets/images/consultation_icon_2.png
    - assets/images/2.0x/consultation_icon_2.png
    - assets/images/3.0x/consultation_icon_2.png
    - assets/images/consultation_icon_3.png
    - assets/images/2.0x/consultation_icon_3.png
    - assets/images/3.0x/consultation_icon_3.png
    - assets/images/consultation_icon_4.png
    - assets/images/2.0x/consultation_icon_4.png
    - assets/images/3.0x/consultation_icon_4.png
    - assets/images/modify_consultation_icon_5.png
    - assets/images/2.0x/modify_consultation_icon_5.png
    - assets/images/3.0x/modify_consultation_icon_5.png
    - assets/images/consultation_icon_6.png
    - assets/images/2.0x/consultation_icon_6.png
    - assets/images/3.0x/consultation_icon_6.png
    - assets/svg/modify_consultation_icon_7.svg
    - assets/svg/modify_consultation_icon_8.svg
    - assets/images/daily_records_1.png
    - assets/images/2.0x/daily_records_1.png
    - assets/images/3.0x/daily_records_1.png
    - assets/images/daily_records_curve_2.png
    - assets/images/2.0x/daily_records_curve_2.png
    - assets/images/3.0x/daily_records_curve_2.png
    - assets/images/scientific_health_1.png
    - assets/images/2.0x/scientific_health_1.png
    - assets/images/3.0x/scientific_health_1.png
    - assets/svg/scientific_health_2.svg
    - assets/images/scientific_health_3.png
    - assets/images/2.0x/scientific_health_3.png
    - assets/images/3.0x/scientific_health_3.png
    - assets/images/scientific_health_4.png
    - assets/images/2.0x/scientific_health_4.png
    - assets/images/3.0x/scientific_health_4.png
    - assets/images/scientific_health_5.png
    - assets/images/2.0x/scientific_health_5.png
    - assets/images/3.0x/scientific_health_5.png
    - assets/svg/scientific_health_6.svg
    - assets/images/scientific_health_7.png
    - assets/images/2.0x/scientific_health_7.png
    - assets/images/3.0x/scientific_health_7.png
    - assets/images/online_consultation.png
    - assets/images/2.0x/online_consultation.png
    - assets/images/3.0x/online_consultation.png
    - assets/images/online_consultation_1.png
    - assets/images/2.0x/online_consultation_1.png
    - assets/images/3.0x/online_consultation_1.png
    - assets/images/daily_records_2.png
    - assets/images/2.0x/daily_records_2.png
    - assets/images/3.0x/daily_records_2.png
    - assets/images/training_courses.png
    - assets/images/2.0x/training_courses.png
    - assets/images/3.0x/training_courses.png
    - assets/images/training_courses_1.png
    - assets/images/2.0x/training_courses_1.png
    - assets/images/3.0x/training_courses_1.png
    - assets/images/training_courses_2.png
    - assets/images/2.0x/training_courses_2.png
    - assets/images/3.0x/training_courses_2.png
    - assets/images/training_courses_3.png
    - assets/images/2.0x/training_courses_3.png
    - assets/images/3.0x/training_courses_3.png
    - assets/svg/modify_switch.svg
    - assets/svg/modify_tag_group_0.svg
    - assets/images/bottom_navigation_home_1.png
    - assets/images/2.0x/bottom_navigation_home_1.png
    - assets/images/3.0x/bottom_navigation_home_1.png
    - assets/images/bottom_navigation_home_2.png
    - assets/images/2.0x/bottom_navigation_home_2.png
    - assets/images/3.0x/bottom_navigation_home_2.png
    - assets/images/cat_1.png
    - assets/images/cat_2.png
    - assets/images/cat_3.png   
    - assets/images/activity_center_cat.png
    - assets/images/2.0x/activity_center_cat.png
    - assets/images/3.0x/activity_center_cat.png
    - assets/images/activity_center_donate_cat.png
    - assets/images/2.0x/activity_center_donate_cat.png
    - assets/images/3.0x/activity_center_donate_cat.png

    
    
    
    
    
    
    
    

    

    
    
    
    

    

    
    
    

    

    

    

    


    

    
    




    